name: testing_example
description: Example project
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: ^2.2.0
  google_maps: ^3.2.0
  http: ^0.11.3

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  mockito: ^2.0.2
  test: '>=0.12.0 <0.13.0'

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
